/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.cosc457final;

import java.util.Objects;

/**
 *
 * @author nk
 */
public class EventsViewSomeWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EventsViewSomeWindow.class.getName());

    /**
     * Creates new form ViewClientWindow
     */
    public EventsViewSomeWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonCancel = new javax.swing.JButton();
        buttonView = new javax.swing.JButton();
        fieldEName = new javax.swing.JFormattedTextField();
        fieldCID = new javax.swing.JFormattedTextField();
        fieldEIsPaid = new javax.swing.JFormattedTextField();
        fieldEID = new javax.swing.JFormattedTextField();
        fieldEDate = new javax.swing.JFormattedTextField();
        fieldETime = new javax.swing.JFormattedTextField();
        fieldELocation = new javax.swing.JFormattedTextField();
        fieldETheme = new javax.swing.JFormattedTextField();
        fieldEColors = new javax.swing.JFormattedTextField();
        fieldEHours = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonView.setText("View");
        buttonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewActionPerformed(evt);
            }
        });

        fieldEName.setText("Event Name");
        fieldEName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldENameActionPerformed(evt);
            }
        });

        fieldCID.setText("Ordering Client ID");
        fieldCID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCIDActionPerformed(evt);
            }
        });

        fieldEIsPaid.setText("Is Event Paid yet?");
        fieldEIsPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEIsPaidActionPerformed(evt);
            }
        });

        fieldEID.setText("Event ID");
        fieldEID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEIDActionPerformed(evt);
            }
        });

        fieldEDate.setText("Event Date");
        fieldEDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEDateActionPerformed(evt);
            }
        });

        fieldETime.setText("Event Time");
        fieldETime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldETimeActionPerformed(evt);
            }
        });

        fieldELocation.setText("Event Location");
        fieldELocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldELocationActionPerformed(evt);
            }
        });

        fieldETheme.setText("Event Theme");
        fieldETheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEThemeActionPerformed(evt);
            }
        });

        fieldEColors.setText("Event Colors");
        fieldEColors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEColorsActionPerformed(evt);
            }
        });

        fieldEHours.setText("Event Hours");
        fieldEHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEHoursActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fieldEIsPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(fieldEColors, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldELocation)
                    .addComponent(fieldEDate, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(fieldEID, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fieldEName)
                        .addComponent(fieldETime)
                        .addComponent(fieldETheme, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(fieldEHours)
                        .addComponent(fieldCID, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(buttonView, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldEID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldEName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldEDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldETime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldELocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldETheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldEColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldEHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldEIsPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel)
                    .addComponent(buttonView))
                .addContainerGap(339, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewActionPerformed
        //FORM SQL QUERY WITH DATA
        if (Objects.nonNull(fieldEID.getText())){
            int EID = Integer.parseInt(fieldEID.getText());
        }
        
        if(fieldEName.getText() != null){
            String name = fieldEName.getText();
        }
        
        if(fieldEDate.getText() != null){
            String date = fieldEDate.getText();
        }
        
        if(fieldETime.getText() != null){
            String time = fieldETime.getText();
        }
        
        if(fieldELocation.getText() != null){
            String location = fieldELocation.getText();
        }
        
        if(fieldETheme.getText() != null){
            String theme = fieldETheme.getText();
        }
        
        if(fieldEColors.getText() != null){
            String colors = fieldEColors.getText();
        }
        
        if(fieldEHours.getText() != null){
            String hours = fieldEHours.getText();
        }
        
        if(fieldEIsPaid.getText() != null){
            String isPaid = fieldEIsPaid.getText(); //TODO: this should probably be a bool lol
        }
        
        if (Objects.nonNull(fieldCID.getText())){
            int CID = Integer.parseInt(fieldCID.getText());
        }        
        
        // TODO: MAKE AND PUSH QUERY
        // only variables the user defines should be used!!

        //THEN CLOSE WINDOW
        this.dispose();
    }//GEN-LAST:event_buttonViewActionPerformed

    private void fieldENameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldENameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldENameActionPerformed

    private void fieldCIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCIDActionPerformed

    private void fieldEIsPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEIsPaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEIsPaidActionPerformed

    private void fieldEIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEIDActionPerformed

    private void fieldEDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEDateActionPerformed

    private void fieldETimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldETimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldETimeActionPerformed

    private void fieldELocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldELocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldELocationActionPerformed

    private void fieldEThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEThemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEThemeActionPerformed

    private void fieldEColorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEColorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEColorsActionPerformed

    private void fieldEHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEHoursActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EventsViewSomeWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonView;
    private javax.swing.JFormattedTextField fieldCID;
    private javax.swing.JFormattedTextField fieldEColors;
    private javax.swing.JFormattedTextField fieldEDate;
    private javax.swing.JFormattedTextField fieldEHours;
    private javax.swing.JFormattedTextField fieldEID;
    private javax.swing.JFormattedTextField fieldEIsPaid;
    private javax.swing.JFormattedTextField fieldELocation;
    private javax.swing.JFormattedTextField fieldEName;
    private javax.swing.JFormattedTextField fieldETheme;
    private javax.swing.JFormattedTextField fieldETime;
    // End of variables declaration//GEN-END:variables
}
