/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.cosc457final;

/**
 *
 * @author nk
 */
public class FinalUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FinalUI.class.getName());

    /**
     * Creates new form FinalUI
     */
    public FinalUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        clientPanel = new javax.swing.JPanel();
        clientSplitPane = new javax.swing.JSplitPane();
        clientAuxDisplay = new javax.swing.JPanel();
        funcListScrollContainer = new javax.swing.JScrollPane();
        clientFuncList = new javax.swing.JList<>();
        mainDisplay = new javax.swing.JPanel();
        tableScrollContainer = new javax.swing.JScrollPane();
        DisplayTable = new javax.swing.JTable();
        contractorPanel = new javax.swing.JPanel();
        contractorSplitPane = new javax.swing.JSplitPane();
        contractorAuxDisplay = new javax.swing.JPanel();
        funcListScrollContainer1 = new javax.swing.JScrollPane();
        contractorFuncList = new javax.swing.JList<>();
        mainDisplay1 = new javax.swing.JPanel();
        tableScrollContainer1 = new javax.swing.JScrollPane();
        DisplayTable1 = new javax.swing.JTable();
        eventPanel = new javax.swing.JPanel();
        eventSplitPane = new javax.swing.JSplitPane();
        eventAuxDisplay = new javax.swing.JPanel();
        funcListScrollContainer2 = new javax.swing.JScrollPane();
        eventFuncList = new javax.swing.JList<>();
        mainDisplay2 = new javax.swing.JPanel();
        tableScrollContainer2 = new javax.swing.JScrollPane();
        DisplayTable2 = new javax.swing.JTable();
        favorPanel = new javax.swing.JPanel();
        favorSplitPane = new javax.swing.JSplitPane();
        FavorAuxDisplay = new javax.swing.JPanel();
        funcListScrollContainer3 = new javax.swing.JScrollPane();
        favorFuncList = new javax.swing.JList<>();
        mainDisplay3 = new javax.swing.JPanel();
        tableScrollContainer3 = new javax.swing.JScrollPane();
        DisplayTable3 = new javax.swing.JTable();
        inventoryPanel = new javax.swing.JPanel();
        inventorySplitPane = new javax.swing.JSplitPane();
        inventoryAuxDisplay = new javax.swing.JPanel();
        funcListScrollContainer4 = new javax.swing.JScrollPane();
        InventoryFuncList = new javax.swing.JList<>();
        mainDisplay4 = new javax.swing.JPanel();
        tableScrollContainer4 = new javax.swing.JScrollPane();
        DisplayTable4 = new javax.swing.JTable();
        workerPanel = new javax.swing.JPanel();
        workerSplitPane = new javax.swing.JSplitPane();
        workerAuxDisplay = new javax.swing.JPanel();
        funcListScrollContainer5 = new javax.swing.JScrollPane();
        WorkerfuncList = new javax.swing.JList<>();
        mainDisplay5 = new javax.swing.JPanel();
        tableScrollContainer5 = new javax.swing.JScrollPane();
        DisplayTable5 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clientFuncList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Add", "Update", "Delete", "View Some", "View All", "View All Renting", "Verify Client Age"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        clientFuncList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                clientFuncListValueChanged(evt);
            }
        });
        funcListScrollContainer.setViewportView(clientFuncList);

        javax.swing.GroupLayout clientAuxDisplayLayout = new javax.swing.GroupLayout(clientAuxDisplay);
        clientAuxDisplay.setLayout(clientAuxDisplayLayout);
        clientAuxDisplayLayout.setHorizontalGroup(
            clientAuxDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientAuxDisplayLayout.createSequentialGroup()
                .addComponent(funcListScrollContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        clientAuxDisplayLayout.setVerticalGroup(
            clientAuxDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(funcListScrollContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        clientSplitPane.setLeftComponent(clientAuxDisplay);

        DisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScrollContainer.setViewportView(DisplayTable);

        javax.swing.GroupLayout mainDisplayLayout = new javax.swing.GroupLayout(mainDisplay);
        mainDisplay.setLayout(mainDisplayLayout);
        mainDisplayLayout.setHorizontalGroup(
            mainDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        mainDisplayLayout.setVerticalGroup(
            mainDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        clientSplitPane.setRightComponent(mainDisplay);

        javax.swing.GroupLayout clientPanelLayout = new javax.swing.GroupLayout(clientPanel);
        clientPanel.setLayout(clientPanelLayout);
        clientPanelLayout.setHorizontalGroup(
            clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clientSplitPane)
                .addContainerGap())
        );
        clientPanelLayout.setVerticalGroup(
            clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clientSplitPane)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Clients", clientPanel);

        contractorFuncList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Add", "Update", "Delete", "View Some", "View All"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        contractorFuncList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                contractorFuncListValueChanged(evt);
            }
        });
        funcListScrollContainer1.setViewportView(contractorFuncList);

        javax.swing.GroupLayout contractorAuxDisplayLayout = new javax.swing.GroupLayout(contractorAuxDisplay);
        contractorAuxDisplay.setLayout(contractorAuxDisplayLayout);
        contractorAuxDisplayLayout.setHorizontalGroup(
            contractorAuxDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contractorAuxDisplayLayout.createSequentialGroup()
                .addComponent(funcListScrollContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        contractorAuxDisplayLayout.setVerticalGroup(
            contractorAuxDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(funcListScrollContainer1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        contractorSplitPane.setLeftComponent(contractorAuxDisplay);

        DisplayTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScrollContainer1.setViewportView(DisplayTable1);

        javax.swing.GroupLayout mainDisplay1Layout = new javax.swing.GroupLayout(mainDisplay1);
        mainDisplay1.setLayout(mainDisplay1Layout);
        mainDisplay1Layout.setHorizontalGroup(
            mainDisplay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        mainDisplay1Layout.setVerticalGroup(
            mainDisplay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        contractorSplitPane.setRightComponent(mainDisplay1);

        javax.swing.GroupLayout contractorPanelLayout = new javax.swing.GroupLayout(contractorPanel);
        contractorPanel.setLayout(contractorPanelLayout);
        contractorPanelLayout.setHorizontalGroup(
            contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contractorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contractorSplitPane)
                .addContainerGap())
        );
        contractorPanelLayout.setVerticalGroup(
            contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contractorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contractorSplitPane)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Contractors", contractorPanel);

        eventFuncList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Add", "Update", "Delete", "View Some", "View All", "View Past Events", "View Upcoming Events" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        eventFuncList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                eventFuncListValueChanged(evt);
            }
        });
        funcListScrollContainer2.setViewportView(eventFuncList);

        javax.swing.GroupLayout eventAuxDisplayLayout = new javax.swing.GroupLayout(eventAuxDisplay);
        eventAuxDisplay.setLayout(eventAuxDisplayLayout);
        eventAuxDisplayLayout.setHorizontalGroup(
            eventAuxDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventAuxDisplayLayout.createSequentialGroup()
                .addComponent(funcListScrollContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        eventAuxDisplayLayout.setVerticalGroup(
            eventAuxDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(funcListScrollContainer2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        eventSplitPane.setLeftComponent(eventAuxDisplay);

        DisplayTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScrollContainer2.setViewportView(DisplayTable2);

        javax.swing.GroupLayout mainDisplay2Layout = new javax.swing.GroupLayout(mainDisplay2);
        mainDisplay2.setLayout(mainDisplay2Layout);
        mainDisplay2Layout.setHorizontalGroup(
            mainDisplay2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollContainer2, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        mainDisplay2Layout.setVerticalGroup(
            mainDisplay2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollContainer2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        eventSplitPane.setRightComponent(mainDisplay2);

        javax.swing.GroupLayout eventPanelLayout = new javax.swing.GroupLayout(eventPanel);
        eventPanel.setLayout(eventPanelLayout);
        eventPanelLayout.setHorizontalGroup(
            eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eventSplitPane)
                .addContainerGap())
        );
        eventPanelLayout.setVerticalGroup(
            eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eventSplitPane)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Events", eventPanel);

        favorFuncList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Add", "Update", "Delete", "View Some", "View All", "View Upcoming Favors"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        favorFuncList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                favorFuncListValueChanged(evt);
            }
        });
        funcListScrollContainer3.setViewportView(favorFuncList);

        javax.swing.GroupLayout FavorAuxDisplayLayout = new javax.swing.GroupLayout(FavorAuxDisplay);
        FavorAuxDisplay.setLayout(FavorAuxDisplayLayout);
        FavorAuxDisplayLayout.setHorizontalGroup(
            FavorAuxDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FavorAuxDisplayLayout.createSequentialGroup()
                .addComponent(funcListScrollContainer3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        FavorAuxDisplayLayout.setVerticalGroup(
            FavorAuxDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(funcListScrollContainer3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        favorSplitPane.setLeftComponent(FavorAuxDisplay);

        DisplayTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScrollContainer3.setViewportView(DisplayTable3);

        javax.swing.GroupLayout mainDisplay3Layout = new javax.swing.GroupLayout(mainDisplay3);
        mainDisplay3.setLayout(mainDisplay3Layout);
        mainDisplay3Layout.setHorizontalGroup(
            mainDisplay3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollContainer3, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        mainDisplay3Layout.setVerticalGroup(
            mainDisplay3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollContainer3, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        favorSplitPane.setRightComponent(mainDisplay3);

        javax.swing.GroupLayout favorPanelLayout = new javax.swing.GroupLayout(favorPanel);
        favorPanel.setLayout(favorPanelLayout);
        favorPanelLayout.setHorizontalGroup(
            favorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(favorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(favorSplitPane)
                .addContainerGap())
        );
        favorPanelLayout.setVerticalGroup(
            favorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(favorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(favorSplitPane)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Favor", favorPanel);

        InventoryFuncList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Add", "Update", "Delete", "View Item", "View All Items", "Sort by Remaining"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        funcListScrollContainer4.setViewportView(InventoryFuncList);

        javax.swing.GroupLayout inventoryAuxDisplayLayout = new javax.swing.GroupLayout(inventoryAuxDisplay);
        inventoryAuxDisplay.setLayout(inventoryAuxDisplayLayout);
        inventoryAuxDisplayLayout.setHorizontalGroup(
            inventoryAuxDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryAuxDisplayLayout.createSequentialGroup()
                .addComponent(funcListScrollContainer4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        inventoryAuxDisplayLayout.setVerticalGroup(
            inventoryAuxDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(funcListScrollContainer4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        inventorySplitPane.setLeftComponent(inventoryAuxDisplay);

        DisplayTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScrollContainer4.setViewportView(DisplayTable4);

        javax.swing.GroupLayout mainDisplay4Layout = new javax.swing.GroupLayout(mainDisplay4);
        mainDisplay4.setLayout(mainDisplay4Layout);
        mainDisplay4Layout.setHorizontalGroup(
            mainDisplay4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollContainer4, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        mainDisplay4Layout.setVerticalGroup(
            mainDisplay4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollContainer4, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        inventorySplitPane.setRightComponent(mainDisplay4);

        javax.swing.GroupLayout inventoryPanelLayout = new javax.swing.GroupLayout(inventoryPanel);
        inventoryPanel.setLayout(inventoryPanelLayout);
        inventoryPanelLayout.setHorizontalGroup(
            inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inventorySplitPane)
                .addContainerGap())
        );
        inventoryPanelLayout.setVerticalGroup(
            inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inventorySplitPane)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Inventory", inventoryPanel);

        WorkerfuncList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Add", "Update", "Delete", "View Worker", "View All Workers"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        funcListScrollContainer5.setViewportView(WorkerfuncList);

        javax.swing.GroupLayout workerAuxDisplayLayout = new javax.swing.GroupLayout(workerAuxDisplay);
        workerAuxDisplay.setLayout(workerAuxDisplayLayout);
        workerAuxDisplayLayout.setHorizontalGroup(
            workerAuxDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workerAuxDisplayLayout.createSequentialGroup()
                .addComponent(funcListScrollContainer5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        workerAuxDisplayLayout.setVerticalGroup(
            workerAuxDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(funcListScrollContainer5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        workerSplitPane.setLeftComponent(workerAuxDisplay);

        DisplayTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScrollContainer5.setViewportView(DisplayTable5);

        javax.swing.GroupLayout mainDisplay5Layout = new javax.swing.GroupLayout(mainDisplay5);
        mainDisplay5.setLayout(mainDisplay5Layout);
        mainDisplay5Layout.setHorizontalGroup(
            mainDisplay5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollContainer5, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        mainDisplay5Layout.setVerticalGroup(
            mainDisplay5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollContainer5, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        workerSplitPane.setRightComponent(mainDisplay5);

        javax.swing.GroupLayout workerPanelLayout = new javax.swing.GroupLayout(workerPanel);
        workerPanel.setLayout(workerPanelLayout);
        workerPanelLayout.setHorizontalGroup(
            workerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(workerSplitPane)
                .addContainerGap())
        );
        workerPanelLayout.setVerticalGroup(
            workerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(workerSplitPane)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Worker", workerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientFuncListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_clientFuncListValueChanged
        // Prevent double events (Swing fires twice during selection change)
        if (evt.getValueIsAdjusting()) {
            return;
        }

        String choice = clientFuncList.getSelectedValue();
        if (choice == null) return;

        switch (choice) {
            case "Add":
                // Create window that allows user to specify query
                new ClientAddWindow().setVisible(true);
                break;

            case "Update":
                // Create window that allows user to specify query
                new ClientUpdateWindow().setVisible(true);
                break;

            case "Delete":
                // Create window that allows user to specify query
                new ClientDeleteWindow().setVisible(true);
                break;

            case "View Some":
                // Create window that allows user to specify query
                new ClientViewSomeWindow().setVisible(true);
                break;

            case "View All":
                //TODO: update table to show *
                break;

            case "View All Renting":
                //TODO: update Table to only show clients currently renting item from inventory
                break;

            case "Verify Client Age":
                //TODO: Update Table to only show clients < 18 years old
                break;
        }
    }//GEN-LAST:event_clientFuncListValueChanged

    private void contractorFuncListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_contractorFuncListValueChanged
        // Prevent double events (Swing fires twice during selection change)
        if (evt.getValueIsAdjusting()) {
            return;
        }

        String choice = contractorFuncList.getSelectedValue();
        if (choice == null) return;

        switch (choice) {
            case "Add":
                // Create window that allows user to specify query
                new ContractorAddWindow().setVisible(true);
                break;

            case "Update":
                // Create window that allows user to specify query
                new ContractorUpdateWindow().setVisible(true);
                break;

            case "Delete":
                // Create window that allows user to specify query
                new ContractorDeleteWindow().setVisible(true);
                break;

            case "View Some":
                // Create window that allows user to specify query
                new ContractorViewSomeWindow().setVisible(true);
                break;

            case "View All":
                //TODO: update table to show *
                break;
        }
    }//GEN-LAST:event_contractorFuncListValueChanged

    private void eventFuncListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_eventFuncListValueChanged
         // Prevent double events (Swing fires twice during selection change)
        if (evt.getValueIsAdjusting()) {
            return;
        }

        String choice = eventFuncList.getSelectedValue();
        if (choice == null) return;

        switch (choice) {
            case "Add":
                // Create window that allows user to specify query
                new EventsAddWindow().setVisible(true);
                break;

            case "Update":
                // Create window that allows user to specify query
                new EventsUpdateWindow().setVisible(true);
                break;

            case "Delete":
                // Create window that allows user to specify query
                new EventsDeleteWindow().setVisible(true);
                break;

            case "View Some":
                // Create window that allows user to specify query
                new EventsViewSomeWindow().setVisible(true);
                break;

            case "View All":
                //TODO: update Event table to show *
                break;
                
            case "View Past Events":
                //TODO: update Event table to show * where EDate < Today()
                break;
            
            case "View Upcoming Events":
                //TODO: update Event table to show * where EDate > Today()
                break;
        }
    }//GEN-LAST:event_eventFuncListValueChanged

    private void favorFuncListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_favorFuncListValueChanged
        // Prevent double events (Swing fires twice during selection change)
        if (evt.getValueIsAdjusting()) {
            return;
        }

        String choice = favorFuncList.getSelectedValue();
        if (choice == null) return;

        switch (choice) {
            case "Add":
                // Create window that allows user to specify query
                new FavorAddWindow().setVisible(true);
                break;

            case "Update":
                // Create window that allows user to specify query
                new FavorUpdateWindow().setVisible(true);
                break;

            case "Delete":
                // Create window that allows user to specify query
                new FavorDeleteWindow().setVisible(true);
                break;

            case "View Some":
                // Create window that allows user to specify query
                new FavorViewSomeWindow().setVisible(true);
                break;

            case "View All":
                //TODO: update Event table to show *
                break;
            
            case "View Upcoming Favors":
                //TODO: update Event table to show * where FDate > Today()
                break;
        }
    }//GEN-LAST:event_favorFuncListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FinalUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DisplayTable;
    private javax.swing.JTable DisplayTable1;
    private javax.swing.JTable DisplayTable2;
    private javax.swing.JTable DisplayTable3;
    private javax.swing.JTable DisplayTable4;
    private javax.swing.JTable DisplayTable5;
    private javax.swing.JPanel FavorAuxDisplay;
    private javax.swing.JList<String> InventoryFuncList;
    private javax.swing.JList<String> WorkerfuncList;
    private javax.swing.JPanel clientAuxDisplay;
    private javax.swing.JList<String> clientFuncList;
    private javax.swing.JPanel clientPanel;
    private javax.swing.JSplitPane clientSplitPane;
    private javax.swing.JPanel contractorAuxDisplay;
    private javax.swing.JList<String> contractorFuncList;
    private javax.swing.JPanel contractorPanel;
    private javax.swing.JSplitPane contractorSplitPane;
    private javax.swing.JPanel eventAuxDisplay;
    private javax.swing.JList<String> eventFuncList;
    private javax.swing.JPanel eventPanel;
    private javax.swing.JSplitPane eventSplitPane;
    private javax.swing.JList<String> favorFuncList;
    private javax.swing.JPanel favorPanel;
    private javax.swing.JSplitPane favorSplitPane;
    private javax.swing.JScrollPane funcListScrollContainer;
    private javax.swing.JScrollPane funcListScrollContainer1;
    private javax.swing.JScrollPane funcListScrollContainer2;
    private javax.swing.JScrollPane funcListScrollContainer3;
    private javax.swing.JScrollPane funcListScrollContainer4;
    private javax.swing.JScrollPane funcListScrollContainer5;
    private javax.swing.JPanel inventoryAuxDisplay;
    private javax.swing.JPanel inventoryPanel;
    private javax.swing.JSplitPane inventorySplitPane;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel mainDisplay;
    private javax.swing.JPanel mainDisplay1;
    private javax.swing.JPanel mainDisplay2;
    private javax.swing.JPanel mainDisplay3;
    private javax.swing.JPanel mainDisplay4;
    private javax.swing.JPanel mainDisplay5;
    private javax.swing.JScrollPane tableScrollContainer;
    private javax.swing.JScrollPane tableScrollContainer1;
    private javax.swing.JScrollPane tableScrollContainer2;
    private javax.swing.JScrollPane tableScrollContainer3;
    private javax.swing.JScrollPane tableScrollContainer4;
    private javax.swing.JScrollPane tableScrollContainer5;
    private javax.swing.JPanel workerAuxDisplay;
    private javax.swing.JPanel workerPanel;
    private javax.swing.JSplitPane workerSplitPane;
    // End of variables declaration//GEN-END:variables
}
