/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.cosc457final;

/**
 *
 * @author nk
 */
public class WorkerUpdateWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WorkerUpdateWindow.class.getName());

    /**
     * Creates new form UpdateWindow
     */
    public WorkerUpdateWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonUpdate = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        fieldWID = new javax.swing.JFormattedTextField();
        fieldWMInit = new javax.swing.JFormattedTextField();
        fieldWFname = new javax.swing.JFormattedTextField();
        fieldWSalary = new javax.swing.JFormattedTextField();
        fieldWLName = new javax.swing.JFormattedTextField();
        fieldWDoB = new javax.swing.JFormattedTextField();
        fieldWAddress = new javax.swing.JFormattedTextField();
        fieldWSSN = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonUpdate.setText("Update");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        fieldWID.setText("ID to Update");
        fieldWID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWIDActionPerformed(evt);
            }
        });

        fieldWMInit.setText("Middle Initial");
        fieldWMInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWMInitActionPerformed(evt);
            }
        });

        fieldWFname.setText("Worker's First Name");
        fieldWFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWFnameActionPerformed(evt);
            }
        });

        fieldWSalary.setText("Salary");
        fieldWSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWSalaryActionPerformed(evt);
            }
        });

        fieldWLName.setText("Last Name");
        fieldWLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWLNameActionPerformed(evt);
            }
        });

        fieldWDoB.setText("Date of Birth");
        fieldWDoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWDoBActionPerformed(evt);
            }
        });

        fieldWAddress.setText("Address");
        fieldWAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWAddressActionPerformed(evt);
            }
        });

        fieldWSSN.setText("SSN");
        fieldWSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWSSNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fieldWMInit, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fieldWID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fieldWFname, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fieldWLName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldWSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldWDoB, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldWAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldWSSN, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(buttonUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldWID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldWFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldWMInit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldWLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldWSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldWDoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldWAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldWSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUpdate)
                    .addComponent(buttonCancel))
                .addContainerGap(237, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        //FORM SQL QUERY WITH DATA
        int WID = Integer.parseInt(fieldWID.getText());
        String fName = fieldWFname.getText();
        String mInit = fieldWMInit.getText();
        String lName = fieldWLName.getText();
        int salary = Integer.parseInt(fieldWSalary.getText());
        String dob = fieldWDoB.getText();
        String address = fieldWAddress.getText();
        int ssn = Integer.parseInt(fieldWSSN.getText());

        // TODO: MAKE AND PUSH QUERY

        //THEN CLOSE WINDOW
        this.dispose();
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void fieldWIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWIDActionPerformed

    private void fieldWFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWFnameActionPerformed

    private void fieldWMInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWMInitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWMInitActionPerformed

    private void fieldWSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWSalaryActionPerformed

    private void fieldWLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWLNameActionPerformed

    private void fieldWDoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWDoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWDoBActionPerformed

    private void fieldWAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWAddressActionPerformed

    private void fieldWSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWSSNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new WorkerUpdateWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JFormattedTextField fieldWAddress;
    private javax.swing.JFormattedTextField fieldWDoB;
    private javax.swing.JFormattedTextField fieldWFname;
    private javax.swing.JFormattedTextField fieldWID;
    private javax.swing.JFormattedTextField fieldWLName;
    private javax.swing.JFormattedTextField fieldWMInit;
    private javax.swing.JFormattedTextField fieldWSSN;
    private javax.swing.JFormattedTextField fieldWSalary;
    // End of variables declaration//GEN-END:variables
}
