/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.cosc457final.FavorWindows;

import java.util.Objects;

/**
 *
 * @author nk
 */
public class FavorViewSomeWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FavorViewSomeWindow.class.getName());

    /**
     * Creates new form ViewClientWindow
     */
    public FavorViewSomeWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonCancel = new javax.swing.JButton();
        buttonView = new javax.swing.JButton();
        fieldFKind = new javax.swing.JFormattedTextField();
        fieldEID = new javax.swing.JFormattedTextField();
        fieldCID = new javax.swing.JFormattedTextField();
        fieldFID = new javax.swing.JFormattedTextField();
        fieldFAmount = new javax.swing.JFormattedTextField();
        fieldFDeadline = new javax.swing.JFormattedTextField();
        fieldFHours = new javax.swing.JFormattedTextField();
        fieldFIsPaid = new javax.swing.JFormattedTextField();
        fieldFMaterialPrice = new javax.swing.JFormattedTextField();
        fieldFIsMade = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonView.setText("View");
        buttonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewActionPerformed(evt);
            }
        });

        fieldFKind.setText("Favor Kind");
        fieldFKind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFKindActionPerformed(evt);
            }
        });

        fieldEID.setText("Belongs to Event ID");
        fieldEID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEIDActionPerformed(evt);
            }
        });

        fieldCID.setText("Ordering Client ID");
        fieldCID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCIDActionPerformed(evt);
            }
        });

        fieldFID.setText("Favor ID");
        fieldFID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFIDActionPerformed(evt);
            }
        });

        fieldFAmount.setText("Favor Amount");
        fieldFAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFAmountActionPerformed(evt);
            }
        });

        fieldFDeadline.setText("Favor Deadline");
        fieldFDeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFDeadlineActionPerformed(evt);
            }
        });

        fieldFHours.setText("Favor Hours");
        fieldFHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFHoursActionPerformed(evt);
            }
        });

        fieldFIsPaid.setText("Is Favor Paid yet?");
        fieldFIsPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFIsPaidActionPerformed(evt);
            }
        });

        fieldFMaterialPrice.setText("Material Price");
        fieldFMaterialPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFMaterialPriceActionPerformed(evt);
            }
        });

        fieldFIsMade.setText("is Favor Made yet?");
        fieldFIsMade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFIsMadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fieldCID, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(fieldFMaterialPrice, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldFHours)
                    .addComponent(fieldFAmount, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(fieldFID, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fieldFKind)
                        .addComponent(fieldFDeadline)
                        .addComponent(fieldFIsPaid)
                        .addComponent(fieldFIsMade)
                        .addComponent(fieldEID, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(buttonView, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldFID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldFKind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldFAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldFDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldFHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldFIsPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldFMaterialPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldFIsMade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldEID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel)
                    .addComponent(buttonView))
                .addContainerGap(339, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewActionPerformed
        //FORM SQL QUERY WITH DATA
        if (Objects.nonNull(fieldFID.getText())){
            int FID = Integer.parseInt(fieldFID.getText());
        }
        
        if(fieldFKind.getText() != null){
            String kind = fieldFKind.getText();
        }
        
        if(fieldFAmount.getText() != null){
            int amount = Integer.parseInt(fieldFAmount.getText());
        }
        
        if(fieldFDeadline.getText() != null){
            String deadline = fieldFDeadline.getText();
        }
        
        if(fieldFHours.getText() != null){
            int hours = Integer.parseInt(fieldFHours.getText());
        }
        
        if(fieldFIsPaid.getText() != null){
            boolean isPaid = Boolean.parseBoolean(fieldFIsPaid.getText());
        }
        
        if(fieldFMaterialPrice.getText() != null){
            int materialPrice = Integer.parseInt(fieldFMaterialPrice.getText());
        }
        
        if(fieldFIsMade.getText() != null){
            boolean isMade = Boolean.parseBoolean(fieldFIsMade.getText());
        }
        
        if(fieldCID.getText() != null){
            int CID = Integer.parseInt(fieldCID.getText());
        }
        
        if (Objects.nonNull(fieldEID.getText())){
            int EID = Integer.parseInt(fieldEID.getText());
        }        
        
        // TODO: MAKE AND PUSH QUERY
        // only variables the user defines should be used!!

        //THEN CLOSE WINDOW
        this.dispose();
    }//GEN-LAST:event_buttonViewActionPerformed

    private void fieldFKindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFKindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFKindActionPerformed

    private void fieldEIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEIDActionPerformed

    private void fieldCIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCIDActionPerformed

    private void fieldFIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFIDActionPerformed

    private void fieldFAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFAmountActionPerformed

    private void fieldFDeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFDeadlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFDeadlineActionPerformed

    private void fieldFHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFHoursActionPerformed

    private void fieldFIsPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFIsPaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFIsPaidActionPerformed

    private void fieldFMaterialPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFMaterialPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFMaterialPriceActionPerformed

    private void fieldFIsMadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFIsMadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFIsMadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FavorViewSomeWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonView;
    private javax.swing.JFormattedTextField fieldCID;
    private javax.swing.JFormattedTextField fieldEID;
    private javax.swing.JFormattedTextField fieldFAmount;
    private javax.swing.JFormattedTextField fieldFDeadline;
    private javax.swing.JFormattedTextField fieldFHours;
    private javax.swing.JFormattedTextField fieldFID;
    private javax.swing.JFormattedTextField fieldFIsMade;
    private javax.swing.JFormattedTextField fieldFIsPaid;
    private javax.swing.JFormattedTextField fieldFKind;
    private javax.swing.JFormattedTextField fieldFMaterialPrice;
    // End of variables declaration//GEN-END:variables
}
