/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.cosc457final.InventoryWindows;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Objects;

/**
 *
 * @author nk
 */
public class InventoryViewSomeWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InventoryViewSomeWindow.class.getName());

    /**
     * Creates new form ViewClientWindow
     */
    public InventoryViewSomeWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldIItemKind = new javax.swing.JFormattedTextField();
        fieldIPrice = new javax.swing.JFormattedTextField();
        buttonCancel = new javax.swing.JButton();
        buttonView = new javax.swing.JButton();
        fieldIQuantity = new javax.swing.JFormattedTextField();
        fieldIReturnDate = new javax.swing.JFormattedTextField();
        fieldIID = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fieldIItemKind.setText("Item Kind");
        fieldIItemKind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIItemKindActionPerformed(evt);
            }
        });

        fieldIPrice.setText("Price");
        fieldIPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIPriceActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonView.setText("View");
        buttonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewActionPerformed(evt);
            }
        });

        fieldIQuantity.setText("Quantity");
        fieldIQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIQuantityActionPerformed(evt);
            }
        });

        fieldIReturnDate.setText("Return Date");
        fieldIReturnDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIReturnDateActionPerformed(evt);
            }
        });

        fieldIID.setText("Item's ID");
        fieldIID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fieldIID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldIPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldIReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fieldIItemKind, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldIQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonView, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldIID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldIPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldIItemKind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldIQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldIReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel)
                    .addComponent(buttonView))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldIItemKindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIItemKindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIItemKindActionPerformed

    private void fieldIPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIPriceActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewActionPerformed
        //FORM SQL QUERY WITH DATA
        int IID = 0;
        int price = 0;
        String itemKind = "";
        int quantity = 0;
        Date returnDate = null;
        
        Boolean hasIID = false;
        Boolean hasprice = false;
        Boolean hasitemKind = false;
        Boolean hasquantity = false;
        Boolean hasreturnDate = false;
        
        if (!fieldIID.getText().isEmpty()){
            IID = Integer.parseInt(fieldIID.getText());
            hasIID = true;
        }
        
        if(!fieldIPrice.getText().isEmpty()){
            price = Integer.parseInt(fieldIPrice.getText());
            hasprice = true;
        }
        
        if(!fieldIItemKind.getText().isEmpty()){
            itemKind = fieldIItemKind.getText();
            hasitemKind = true;
        }
        
        if(!fieldIQuantity.getText().isEmpty()){
            quantity = Integer.parseInt(fieldIQuantity.getText());
            hasquantity = true;
        }
        
        if(!fieldIReturnDate.getText().isEmpty()){
            returnDate = java.sql.Date.valueOf(fieldIReturnDate.getText());
            hasreturnDate = true;
        }

        String query = "SELECT * FROM Inventory WHERE 1=1";/////////////QUERY BY SELENA//////////////
        
        if (hasIID){
            query += " AND IID = ?";
        }
        
        if(hasprice){
            query += " AND IPrice = ?";
        }
        
        if(hasitemKind){
            query += " AND IItemKind = ?";////CHECK VARIABLE NAMES W TABLE FOR SQL////
        }
        
        if(hasquantity){
            query += " AND IQuantity = ?";
        }
        
        if(hasreturnDate){
            query += " AND IReturnDate = ?";
        }
        
        try{
		Class.forName("com.mysql.cj.jdbc.Driver");
	} catch (ClassNotFoundException e){
		System.out.println(e);
	}
		
		final String ID = "narella1";
		final String PW = "COSC*emh8v";
		final String SERVER = "jdbc:mysql://triton.towson.edu:3360/narella1db?serverTimezone=EST";
                
        try{
		Connection con = DriverManager.getConnection(SERVER, ID, PW);
                PreparedStatement ps = con.prepareStatement(query);
                
                int in = 1;
                
                if (hasIID){
                    ps.setInt(in++, IID);
                }

                if(hasprice){
                    ps.setInt(in++, price);
                }

                if(hasitemKind){
                    ps.setString(in++, itemKind);
                }

                if(hasquantity){
                    ps.setInt(in++, quantity);
                }

                if(hasreturnDate){
                    ps.setDate(in++, returnDate);
                }
                
                ResultSet rs = ps.executeQuery();
                
                while(rs.next()){
                    int pIID = rs.getInt("IID");
                    int pprice = rs.getInt("IPrice");
                    String pitemKind = rs.getString("IItemKind");
                    int pquantity = rs.getInt("IQuantity");
                    Date preturnDate = rs.getDate("IReturnDate");
                    System.out.println("IID: "+pIID+", IPrice: "+pprice+", IItemKind: "+pitemKind+", IQuantity: "+pquantity+", IReturnDate: "+preturnDate);
                }
                
            } catch (SQLException e){
			System.err.println(e);
            }
        // TODO: MAKE AND PUSH QUERY
        // only variables the user defines should be used!!

        //THEN CLOSE WINDOW
        this.dispose();
    }//GEN-LAST:event_buttonViewActionPerformed

    private void fieldIQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIQuantityActionPerformed

    private void fieldIReturnDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIReturnDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIReturnDateActionPerformed

    private void fieldIIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InventoryViewSomeWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonView;
    private javax.swing.JFormattedTextField fieldIID;
    private javax.swing.JFormattedTextField fieldIItemKind;
    private javax.swing.JFormattedTextField fieldIPrice;
    private javax.swing.JFormattedTextField fieldIQuantity;
    private javax.swing.JFormattedTextField fieldIReturnDate;
    // End of variables declaration//GEN-END:variables
}
