/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.cosc457final.EventWindows;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author nk
 */
public class EventCalculateCostWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EventCalculateCostWindow.class.getName());

    /**
     * Creates new form DeleteWindow
     */
    public EventCalculateCostWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldEID = new javax.swing.JFormattedTextField();
        buttonCalculateCost = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fieldEID.setText("Event ID");
        fieldEID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEIDActionPerformed(evt);
            }
        });

        buttonCalculateCost.setText("Calculate");
        buttonCalculateCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalculateCostActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fieldEID)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCalculateCost)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldEID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel)
                    .addComponent(buttonCalculateCost))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldEIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEIDActionPerformed

    private void buttonCalculateCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculateCostActionPerformed
        //FORM SQL QUERY WITH DATA
        int EID = Integer.parseInt(fieldEID.getText());

        try{
			Class.forName("com.mysql.cj.jdbc.Driver");
		} catch (ClassNotFoundException e){
			System.out.println(e);
		}
		
		final String ID = "narella1";
		final String PW = "COSC*emh8v";
		final String SERVER = "jdbc:mysql://triton.towson.edu:3360/narella1db?serverTimezone=EST";
                
        try{
		Connection con = DriverManager.getConnection(SERVER, ID, PW);
                PreparedStatement ps = con.prepareStatement("SELECT ContID FROM EventContractors WHERE EID = ?");
                PreparedStatement ps2 = con.prepareStatement("SELECT ContID, SUM(Cost) AS contCost FROM Contractor WHERE ContID = ?");
                PreparedStatement ps3 = con.prepareStatement("SELECT FID, FHours, SUM(FMaterialPrice) AS favCost FROM Favor WHERE EID = ?");
                PreparedStatement ps4 = con.prepareStatement("SELECT IID FROM EventBorrows WHERE EID = ?");
                PreparedStatement ps5 = con.prepareStatement("SELECT IID, SUM(IPrice) AS iCost FROM Inventory WHERE IID = ?");
                PreparedStatement ps6 = con.prepareStatement("SELECT EID, EHours FROM Event WHERE EID = ?");
                
                ps.setInt(1, EID);
                ResultSet rs = ps.executeQuery();
                int contCost = 0;
                
                while (rs.next()) {
                    ps2.setInt(1, rs.getInt("ContID"));
                    ResultSet rs2 = ps2.executeQuery();
                        if(rs.next()){
                            contCost += rs2.getInt("contCost");
                        }
                }
                
                ps3.setInt(1, EID);
                ResultSet rs3 = ps3.executeQuery();
                int favCost = 0;
                
                while (rs3.next()){
                    favCost += rs3.getInt("favCost") + (15*rs3.getInt("FHours"));
                }
                
                ps4.setInt(1, EID);
                ResultSet rs4 = ps4.executeQuery();
                int iCost = 0;
                
                while (rs4.next()){
                    ps5.setInt(1, rs4.getInt("IID"));
                    ResultSet rs5 = ps5.executeQuery();
                    if(rs5.next()){
                        iCost += rs5.getInt("iCost");
                    }
                }
                
                ps6.setInt(1, EID);
                ResultSet rs6 = ps6.executeQuery();
                int laborCost = 0;
                
                if(rs6.next()){
                    laborCost = 15 * rs6.getInt("EHours");
                }
                
                int totalCost = contCost + favCost + iCost + laborCost;
                
                System.out.println("Total Cost for Event: "+ EID +" = $"+ totalCost);
                  
            } catch (SQLException e){
			System.err.println(e);
            }
        // TODO: MAKE AND PUSH QUERY
            // should the result pop up as a new window to 
            // display result since its only 1 value?

        //THEN CLOSE WINDOW
        this.dispose();
    }//GEN-LAST:event_buttonCalculateCostActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EventCalculateCostWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalculateCost;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JFormattedTextField fieldEID;
    // End of variables declaration//GEN-END:variables
}
