/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.cosc457final.EventWindows;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author nk
 */
public class EventSumSalesWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EventSumSalesWindow.class.getName());

    /**
     * Creates new form DeleteWindow
     */
    public EventSumSalesWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldFromDate = new javax.swing.JFormattedTextField();
        buttonCalculate = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        fieldToDate = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fieldFromDate.setText("From:");
        fieldFromDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFromDateActionPerformed(evt);
            }
        });

        buttonCalculate.setText("Calculate");
        buttonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalculateActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        fieldToDate.setText("To:");
        fieldToDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldToDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fieldFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldToDate))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCalculate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel)
                    .addComponent(buttonCalculate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldFromDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFromDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFromDateActionPerformed

    private void buttonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculateActionPerformed
        //FORM SQL QUERY WITH DATA
        Date fromDate = java.sql.Date.valueOf(fieldFromDate.getText().trim());
        Date toDate = java.sql.Date.valueOf(fieldToDate.getText().trim());

        try{
			Class.forName("com.mysql.cj.jdbc.Driver");
		} catch (ClassNotFoundException e){
			System.out.println(e);
		}
		
		final String ID = "narella1";
		final String PW = "COSC*emh8v";
		final String SERVER = "jdbc:mysql://triton.towson.edu:3360/narella1db?serverTimezone=EST";
                
        try{
		Connection con = DriverManager.getConnection(SERVER, ID, PW);
                PreparedStatement ps = con.prepareStatement("SELECT EID FROM Event WHERE EDate BETWEEN ? and ?");
                PreparedStatement ps2 = con.prepareStatement("SELECT EHours FROM Event WHERE EID = ?");
                PreparedStatement ps3 = con.prepareStatement("SELECT ContID FROM EventContractors WHERE EID = ?");
                PreparedStatement ps4 = con.prepareStatement("SELECT ContID, SUM(Cost) AS contCost FROM Contractor WHERE ContID = ?");
                PreparedStatement ps5 = con.prepareStatement("SELECT FHours, SUM(FMaterialPrice) AS favCost FROM Favor WHERE EID = ?");
                PreparedStatement ps6 = con.prepareStatement("SELECT IID FROM EventBorrows WHERE EID = ?");
                PreparedStatement ps7 = con.prepareStatement("SELECT IID, SUM(IPrice) AS iCost FROM Inventory WHERE IID = ?");
                
                ps.setDate(1, fromDate);
                ps.setDate(2, toDate);
                ResultSet rs = ps.executeQuery();
                int laborCost = 0;
                int EID = 0;
                
                while(rs.next()){
                    EID = rs.getInt("EID");
                    ps2.setInt(1, EID);
                    ResultSet rs2 = ps2.executeQuery();
                    if(rs2.next()){
                        laborCost = 15 * rs2.getInt("EHours");
                    }
                }
                
                ps3.setInt(1, EID);
                ResultSet rs3 = ps3.executeQuery();
                int contCost = 0;
                
                while(rs3.next()){
                    ps4.setInt(1, rs3.getInt("ContID"));
                    ResultSet rs4 = ps4.executeQuery();
                    if(rs4.next()){
                        contCost += rs4.getInt("contCost");
                    }
                }
                    
                ps5.setInt(1, EID);
                ResultSet rs5 = ps5.executeQuery();                
                int favCost = 0;
                
                if (rs5.next()) {
                    favCost = rs5.getInt("favCost") + (15*rs5.getInt("FHours"));
                }
                
                ps6.setInt(1, EID);
                ResultSet rs6 = ps6.executeQuery();
                int iCost = 0;
                
                while(rs6.next()){
                    ps7.setInt(1, rs6.getInt("IID"));
                    ResultSet rs7 = ps7.executeQuery();
                    if (rs7.next()) {
                        iCost = rs7.getInt("iCost");
                    }
                }
                
                int totalCost = contCost + favCost + iCost + laborCost;
                
                System.out.println("Total Cost for Events between "+ fromDate +" and "+ toDate +" = $"+ totalCost);
                
                } catch (SQLException e){
			System.err.println(e);
            }
        // TODO: MAKE AND PUSH QUERY
            // should the result pop up as a new window to 
            // display result since its only 1 value?

        //THEN CLOSE WINDOW
        this.dispose();
    }//GEN-LAST:event_buttonCalculateActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void fieldToDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldToDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldToDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EventSumSalesWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalculate;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JFormattedTextField fieldFromDate;
    private javax.swing.JFormattedTextField fieldToDate;
    // End of variables declaration//GEN-END:variables
}
