/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.cosc457final.WorkerWindows;

/**
 *
 * @author nk
 */
public class WorkerAddWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WorkerAddWindow.class.getName());

    /**
     * Creates new form AddWindow
     */
    public WorkerAddWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldWFName = new javax.swing.JFormattedTextField();
        fieldWLName = new javax.swing.JFormattedTextField();
        fieldWSalary = new javax.swing.JFormattedTextField();
        fieldWDoB = new javax.swing.JFormattedTextField();
        buttonSave = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        fieldSSN = new javax.swing.JFormattedTextField();
        fieldWAddress = new javax.swing.JFormattedTextField();
        fieldWMInit = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fieldWFName.setText("Worker's First Name");
        fieldWFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWFNameActionPerformed(evt);
            }
        });

        fieldWLName.setText("Last Name");

        fieldWSalary.setText("Salary");
        fieldWSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWSalaryActionPerformed(evt);
            }
        });

        fieldWDoB.setText("Date of Birth");
        fieldWDoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWDoBActionPerformed(evt);
            }
        });

        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        fieldSSN.setText("SSN");
        fieldSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSSNActionPerformed(evt);
            }
        });

        fieldWAddress.setText("Address");
        fieldWAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWAddressActionPerformed(evt);
            }
        });

        fieldWMInit.setText("Middle Initial");
        fieldWMInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWMInitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldWFName)
                    .addComponent(fieldWLName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldWDoB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(fieldSSN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldWAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(fieldWMInit, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(fieldWSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(buttonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldWFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldWMInit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldWLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldWSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldWDoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldWAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel)
                    .addComponent(buttonSave))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldWFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWFNameActionPerformed

    private void fieldWSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWSalaryActionPerformed

    private void fieldWDoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWDoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWDoBActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        //FORM SQL QUERY WITH DATA
        String fName = fieldWFName.getText();
        String mInit = fieldWMInit.getText();
        String lName = fieldWLName.getText();
        int salary = Integer.parseInt(fieldWSalary.getText());
        String dob = fieldWDoB.getText();
        String address = fieldWAddress.getText();
        int SSN = Integer.parseInt(fieldSSN.getText());
        
        // TODO: MAKE AND PUSH QUERY
        
        //THEN CLOSE WINDOW
        this.dispose();
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        //just close window on 'Cancel'
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void fieldSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSSNActionPerformed

    private void fieldWAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWAddressActionPerformed

    private void fieldWMInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWMInitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWMInitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new WorkerAddWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonSave;
    private javax.swing.JFormattedTextField fieldSSN;
    private javax.swing.JFormattedTextField fieldWAddress;
    private javax.swing.JFormattedTextField fieldWDoB;
    private javax.swing.JFormattedTextField fieldWFName;
    private javax.swing.JFormattedTextField fieldWLName;
    private javax.swing.JFormattedTextField fieldWMInit;
    private javax.swing.JFormattedTextField fieldWSalary;
    // End of variables declaration//GEN-END:variables
}
