/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.cosc457final.WorkerWindows;

import java.util.Objects;

/**
 *
 * @author nk
 */
public class WorkerViewSomeWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WorkerViewSomeWindow.class.getName());

    /**
     * Creates new form ViewClientWindow
     */
    public WorkerViewSomeWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonCancel = new javax.swing.JButton();
        buttonView = new javax.swing.JButton();
        fieldWFName = new javax.swing.JFormattedTextField();
        fieldWID = new javax.swing.JFormattedTextField();
        fieldWMInit = new javax.swing.JFormattedTextField();
        fieldWLName = new javax.swing.JFormattedTextField();
        fieldWSalary = new javax.swing.JFormattedTextField();
        fieldWDoB = new javax.swing.JFormattedTextField();
        fieldWAddress = new javax.swing.JFormattedTextField();
        fieldSSN = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonView.setText("View");
        buttonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewActionPerformed(evt);
            }
        });

        fieldWFName.setText("First Name");
        fieldWFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWFNameActionPerformed(evt);
            }
        });

        fieldWID.setText("Worker ID");
        fieldWID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWIDActionPerformed(evt);
            }
        });

        fieldWMInit.setText("Middle Initial");
        fieldWMInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWMInitActionPerformed(evt);
            }
        });

        fieldWLName.setText("Last Name");
        fieldWLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWLNameActionPerformed(evt);
            }
        });

        fieldWSalary.setText("Salary");
        fieldWSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWSalaryActionPerformed(evt);
            }
        });

        fieldWDoB.setText("Date of Birth");
        fieldWDoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWDoBActionPerformed(evt);
            }
        });

        fieldWAddress.setText("Address");
        fieldWAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWAddressActionPerformed(evt);
            }
        });

        fieldSSN.setText("SSN");
        fieldSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSSNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fieldWAddress, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldWSalary)
                    .addComponent(fieldWMInit, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(fieldWID, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fieldWFName)
                        .addComponent(fieldWLName)
                        .addComponent(fieldWDoB, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(fieldSSN))
                    .addComponent(buttonView, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldWID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldWFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldWMInit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldWLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldWSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldWDoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldWAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel)
                    .addComponent(buttonView))
                .addContainerGap(368, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewActionPerformed
        //FORM SQL QUERY WITH DATA
        if (Objects.nonNull(fieldWID.getText())){
            int WID = Integer.parseInt(fieldWID.getText());
        }
        
        if(fieldWFName.getText() != null){
            String fName = fieldWFName.getText();
        }
        
        if(fieldWMInit.getText() != null){
            String mInit = fieldWMInit.getText();
        }
        
        if(fieldWLName.getText() != null){
            String lName = fieldWLName.getText();
        }
        
        if(fieldWSalary.getText() != null){
            int salary = Integer.parseInt(fieldWSalary.getText());
        }
        
        if(fieldWDoB.getText() != null){
            String dob = fieldWDoB.getText();
        }
        
        if(fieldWAddress.getText() != null){
            String address = fieldWAddress.getText();
        }
        
        if(fieldSSN.getText() != null){
            int ssn = Integer.parseInt(fieldSSN.getText());
        }
        
        // TODO: MAKE AND PUSH QUERY
        // only variables the user defines should be used!!

        //THEN CLOSE WINDOW
        this.dispose();
    }//GEN-LAST:event_buttonViewActionPerformed

    private void fieldWFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWFNameActionPerformed

    private void fieldWIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWIDActionPerformed

    private void fieldWMInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWMInitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWMInitActionPerformed

    private void fieldWLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWLNameActionPerformed

    private void fieldWSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWSalaryActionPerformed

    private void fieldWDoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWDoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWDoBActionPerformed

    private void fieldWAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWAddressActionPerformed

    private void fieldSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSSNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new WorkerViewSomeWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonView;
    private javax.swing.JFormattedTextField fieldSSN;
    private javax.swing.JFormattedTextField fieldWAddress;
    private javax.swing.JFormattedTextField fieldWDoB;
    private javax.swing.JFormattedTextField fieldWFName;
    private javax.swing.JFormattedTextField fieldWID;
    private javax.swing.JFormattedTextField fieldWLName;
    private javax.swing.JFormattedTextField fieldWMInit;
    private javax.swing.JFormattedTextField fieldWSalary;
    // End of variables declaration//GEN-END:variables
}
